export const ALLOWED_SETTING_KEYS = new Set([
  'site_title',
  'contact_email',
  'phone',
  'address',
  'whatsapp',
  'google_rating',
  'review_count',
  'years_experience',
  'clients_count',
  'opening_hours',
  'opening_hours_sat',
  'logo_url',
  'trusted_clients',
  'hp_hero',
  'hp_services',
  'hp_whyus',
  'hp_cta',
  'pricing_min_hourly_rate',
  'pricing_target_hourly_rate',
  'pricing_min_margin',
  'pricing_payroll_burden',
  'pricing_vat_rate',
  'pricing_public_range',
  'legal_templates_approved',
  'legal_company_name',
  'legal_representative',
  'legal_street',
  'legal_zip',
  'legal_city',
  'legal_tax_number',
  'legal_vat_id',
  'legal_iban',
  'legal_bic',
  'legal_bank_name',
  'legal_signature_name',
  'legal_page_agb',
  'legal_page_datenschutz',
  'legal_page_impressum',
]);

export function isAllowedSettingKey(key: string): boolean {
  return ALLOWED_SETTING_KEYS.has(key);
}
