'use client';

import { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, Save, ShieldCheck } from 'lucide-react';
import { AdminPageHeader, AdminPanel, AdminStatus, EmptyState } from '@/components/admin/AdminUi';
import { useOperations } from '@/components/admin/useOperations';

const sections = [
  ['unternehmen', 'Unternehmen'], ['kalkulation', 'Kalkulation'], ['leistungen', 'Leistungsstandards'], ['dokumente', 'Dokumentvorlagen'], ['kommunikation', 'Kommunikation'], ['sicherheit', 'Benutzer & Sicherheit'],
] as const;

const companyFields = [
  ['legal_company_name','Firmenname'], ['legal_representative','Vertretungsberechtigte Person / Familie'], ['legal_street','Straße'], ['legal_zip','PLZ'], ['legal_city','Ort'], ['contact_email','E-Mail'], ['phone','Telefon'], ['legal_tax_number','Steuernummer'], ['legal_vat_id','USt-IdNr. (beginnt mit DE)'], ['legal_iban','IBAN'], ['legal_bic','BIC'], ['legal_bank_name','Bank'], ['legal_signature_name','Name für Unterschriftszeile'],
] as const;

const pricingFields = [
  ['pricing_min_hourly_rate','Mindest-Verrechnungssatz','38'], ['pricing_target_hourly_rate','Ziel-Verrechnungssatz','42'], ['pricing_min_margin','Mindestmarge in %','20'], ['pricing_payroll_burden','Lohnnebenkosten / Zuschlag in %','75'], ['pricing_vat_rate','Umsatzsteuer in %','19'], ['pricing_public_range','Öffentlicher Preiskorridor ± %','12'],
] as const;

export default function EinstellungenPage() {
  const { data, loading, create } = useOperations();
  const [tab, setTab] = useState<(typeof sections)[number][0]>('unternehmen');
  const [settings, setSettings] = useState<Record<string,string>>({});
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');

  useEffect(() => { fetch('/api/admin/settings').then(response => response.json()).then(items => { if (Array.isArray(items)) setSettings(Object.fromEntries(items.map(item => [item.key,item.value]))); }); }, []);
  async function saveSettings(keys: readonly (readonly string[])[]) {
    setError(''); setMessage('');
    const payload = Object.fromEntries(keys.map(([key]) => [key, settings[key] || '']));
    const response = await fetch('/api/admin/settings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) });
    if (!response.ok) { const result = await response.json(); setError(result.error || 'Speichern fehlgeschlagen.'); return; }
    setMessage('Einstellungen wurden gespeichert.');
  }
  const legalReady = ['legal_company_name','legal_representative','legal_street','legal_zip','legal_city','legal_tax_number'].every(key => settings[key]?.trim());
  return <><AdminPageHeader title="Einstellungen" description="Unternehmensdaten, Kalkulationsschutz und Vorlagen werden zentral und nachvollziehbar verwaltet." /><div className="admin-tabs">{sections.map(([key,label]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => { setTab(key); setMessage(''); setError(''); }}>{label}</button>)}</div>
    {message ? <div className="mb-5 text-sm text-emerald-700">{message}</div> : null}{error ? <div className="mb-5 text-sm text-red-600">{error}</div> : null}
    {tab === 'unternehmen' ? <div className="admin-grid"><AdminPanel title="Unternehmens- und Vertragsdaten" description="Diese Angaben erscheinen auf Angeboten, Verträgen und Protokollen."><div className="admin-form"><div className="admin-form-grid">{companyFields.map(([key,label]) => <SettingField key={key} label={label} value={settings[key] || ''} onChange={value => setSettings(current => ({ ...current, [key]: value }))} />)}</div><button className="admin-button" onClick={() => saveSettings(companyFields)}><Save size={15} /> Unternehmensdaten speichern</button></div></AdminPanel><AdminPanel title="Dokumentfreigabe"><div className="admin-form">{legalReady ? <div className="flex gap-3 text-emerald-700"><CheckCircle2 size={20} /><div><strong className="text-sm">Pflichtdaten vollständig</strong><p className="mt-1 text-xs leading-5 text-slate-500">Die rechtliche Vorlagenprüfung bleibt dennoch separat erforderlich.</p></div></div> : <div className="flex gap-3 text-amber-700"><AlertTriangle size={20} /><div><strong className="text-sm">Pflichtdaten unvollständig</strong><p className="mt-1 text-xs leading-5 text-slate-500">Finale Vertragsfreigaben bleiben gesperrt.</p></div></div>}<div className="admin-field"><label>Vorlagen rechtlich geprüft</label><select value={settings.legal_templates_approved || 'false'} onChange={event => setSettings(current => ({ ...current, legal_templates_approved: event.target.value }))}><option value="false">Nein - Entwurfsstatus erzwingen</option><option value="true">Ja - fachliche Prüfung dokumentiert</option></select></div><button className="admin-button admin-button-secondary" onClick={() => saveSettings([['legal_templates_approved']])}><ShieldCheck size={15} /> Freigabestatus speichern</button></div></AdminPanel></div> : null}
    {tab === 'kalkulation' ? <AdminPanel title="Globale Kalkulationsstandards" description="38 € und 20 % sind technische Untergrenzen und können nicht unterschritten werden."><div className="admin-form"><div className="admin-form-grid">{pricingFields.map(([key,label,fallback]) => <SettingField key={key} label={label} type="number" value={settings[key] || fallback} onChange={value => setSettings(current => ({ ...current, [key]: value }))} />)}</div><div className="flex gap-2"><AdminStatus tone="success">Mindest-Verrechnungssatz 38 €</AdminStatus><AdminStatus tone="success">Mindestmarge 20 %</AdminStatus></div><button className="admin-button" onClick={() => saveSettings(pricingFields)}><Save size={15} /> Standards speichern</button></div></AdminPanel> : null}
    {tab === 'leistungen' ? <AdminPanel title="Leistungsstandards" description="Leistungswerte dienen als Startpunkt. Jede Objektkalkulation bleibt individuell.">{loading ? <EmptyState title="Standards werden geladen" text="Einen Moment bitte." /> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Dienstleistung</th><th>Einheit</th><th>Leistungswert / Std.</th><th>Tariflohn</th><th>Material</th><th>Rüstzeit</th><th></th></tr></thead><tbody>{data.priceSettings.map(item => <PriceRow key={item.id} item={item} save={create} />)}</tbody></table></div>}</AdminPanel> : null}
    {tab === 'dokumente' ? <AdminPanel title="Vorlagen je Dienstleistung" description="Verträge, Angebote, Leistungsverzeichnisse, Objekt-Checklisten, SOPs und Zusatzleistungskataloge.">{loading ? <EmptyState title="Vorlagen werden geladen" text="Einen Moment bitte." /> : <div className="admin-list">{data.templates.map(template => <TemplateRow key={template.id} template={template} save={create} />)}</div>}</AdminPanel> : null}
    {tab === 'kommunikation' ? <AdminPanel title="Vorlagen für Kundenkommunikation" description="Fertige Texte mit Platzhaltern für wiederkehrende Abläufe.">{loading ? <EmptyState title="Vorlagen werden geladen" text="Einen Moment bitte." /> : <div className="admin-list">{data.communication.map(template => <CommunicationRow key={template.id} template={template} save={create} />)}</div>}</AdminPanel> : null}
    {tab === 'sicherheit' ? <div className="admin-grid"><AdminPanel title="Zugriffsschutz"><div className="admin-form"><div className="flex gap-3"><ShieldCheck className="text-emerald-600" size={22} /><div><strong className="text-sm">Admin-Rolle erforderlich</strong><p className="mt-1 text-xs leading-5 text-slate-500">CRM, Kalkulationen, interne Preise und Dokumente werden ausschließlich über geschützte Admin-Routen geladen.</p></div></div><AdminStatus tone="success">Rollenprüfung aktiv</AdminStatus></div></AdminPanel><AdminPanel title="Passwort ändern"><PasswordForm /></AdminPanel></div> : null}
  </>;
}

function SettingField({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value:string) => void; type?: string }) { return <div className="admin-field"><label>{label}</label><input type={type} value={value} onChange={event => onChange(event.target.value)} /></div>; }
function PriceRow({ item, save }: { item: any; save: (payload: Record<string, unknown>) => Promise<any> }) { const [value,setValue] = useState(item); const [saved,setSaved] = useState(false); return <tr><td><strong>{value.title}</strong></td><td>{value.unit}</td><td><input className="w-20 border rounded-md p-2" type="number" value={value.performancePerHour} onChange={event => setValue({ ...value, performancePerHour: Number(event.target.value) })} /></td><td><input className="w-20 border rounded-md p-2" type="number" value={value.wagePerHour} onChange={event => setValue({ ...value, wagePerHour: Number(event.target.value) })} /></td><td><input className="w-16 border rounded-md p-2" type="number" value={value.materialPercent} onChange={event => setValue({ ...value, materialPercent: Number(event.target.value) })} /> %</td><td><input className="w-16 border rounded-md p-2" type="number" value={value.setupMinutes} onChange={event => setValue({ ...value, setupMinutes: Number(event.target.value) })} /> Min.</td><td><button className="admin-button admin-button-secondary" onClick={async () => { await save({ action: 'priceSetting', ...value }); setSaved(true); }}>{saved ? 'Gespeichert' : 'Speichern'}</button></td></tr>; }
function TemplateRow({ template, save }: { template:any; save:(payload:Record<string,unknown>)=>Promise<any> }) { const [open,setOpen]=useState(false); const [content,setContent]=useState(template.content); return <div className="py-3 border-b last:border-0"><div className="flex items-center justify-between gap-4"><div><strong className="text-sm text-slate-700">{template.title}</strong><small className="block mt-1 text-slate-400">{template.category} · {template.legalApproved ? 'rechtlich freigegeben' : 'Entwurf'}</small></div><button className="admin-button admin-button-secondary" onClick={() => setOpen(value => !value)}>{open ? 'Schließen' : 'Bearbeiten'}</button></div>{open ? <div className="admin-form px-0 pb-0"><div className="admin-field"><label>Vorlagentext</label><textarea className="min-h-[260px]" value={content} onChange={event => setContent(event.target.value)} /></div><button className="admin-button" onClick={() => save({ action:'documentTemplate', id:template.id, title:template.title, content, active:template.active, legalApproved:template.legalApproved })}>Vorlage speichern</button></div> : null}</div>; }
function CommunicationRow({ template, save }: { template:any; save:(payload:Record<string,unknown>)=>Promise<any> }) { const [open,setOpen]=useState(false); const [subject,setSubject]=useState(template.subject); const [content,setContent]=useState(template.content); return <div className="py-3 border-b last:border-0"><div className="flex justify-between gap-4"><div><strong className="text-sm text-slate-700">{template.title}</strong><small className="block mt-1 text-slate-400">{template.subject}</small></div><button className="admin-button admin-button-secondary" onClick={() => setOpen(value=>!value)}>{open?'Schließen':'Bearbeiten'}</button></div>{open?<div className="admin-form px-0 pb-0"><div className="admin-field"><label>Betreff</label><input value={subject} onChange={event=>setSubject(event.target.value)}/></div><div className="admin-field"><label>Text</label><textarea value={content} onChange={event=>setContent(event.target.value)}/></div><button className="admin-button" onClick={()=>save({action:'communicationTemplate',id:template.id,title:template.title,subject,content,active:template.active})}>Text speichern</button></div>:null}</div>; }
function PasswordForm() { const [form,setForm]=useState({current:'',next:'',confirm:''}); const [message,setMessage]=useState(''); async function submit(event:React.FormEvent){event.preventDefault(); if(form.next!==form.confirm){setMessage('Die neuen Passwörter stimmen nicht überein.');return;} const response=await fetch('/api/admin/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword:form.current,newPassword:form.next})}); const result=await response.json(); setMessage(response.ok?'Passwort wurde geändert.':result.error||'Änderung fehlgeschlagen.');} return <form className="admin-form" onSubmit={submit}><div className="admin-field"><label>Aktuelles Passwort</label><input type="password" value={form.current} onChange={event=>setForm({...form,current:event.target.value})}/></div><div className="admin-field"><label>Neues Passwort</label><input type="password" minLength={8} value={form.next} onChange={event=>setForm({...form,next:event.target.value})}/></div><div className="admin-field"><label>Neues Passwort bestätigen</label><input type="password" value={form.confirm} onChange={event=>setForm({...form,confirm:event.target.value})}/></div>{message?<p className="text-xs text-slate-600">{message}</p>:null}<button className="admin-button">Passwort ändern</button></form>; }
