'use client';

import { useState } from 'react';
import { Package, Plus, Wrench } from 'lucide-react';
import { AdminMetric, AdminPageHeader, AdminPanel, AdminStatus, EmptyState } from '@/components/admin/AdminUi';
import { useOperations } from '@/components/admin/useOperations';
import { formatEuro } from '@/lib/pricing-engine';

export default function InventarPage() {
  const { data, loading, create } = useOperations();
  const [tab, setTab] = useState<'material' | 'equipment'>('material');
  const [showForm, setShowForm] = useState(false);
  const [message, setMessage] = useState('');
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); try { await create({ action: tab, ...Object.fromEntries(new FormData(event.currentTarget)) }); event.currentTarget.reset(); setShowForm(false); setMessage('Eintrag wurde gespeichert.'); } catch (err) { setMessage(err instanceof Error ? err.message : 'Fehler'); } }
  const lowStock = data.materials.filter(item => item.stock <= item.minimumStock).length;
  const maintenance = data.equipment.filter(item => item.nextMaintenance && new Date(item.nextMaintenance) <= new Date(Date.now() + 30 * 86400000)).length;
  return <><AdminPageHeader title="Material & Geräte" description="Kleine, zuverlässige Bestands- und Wartungsübersicht ohne unnötige Warenwirtschaft." action={<button className="admin-button" onClick={() => setShowForm(value => !value)}><Plus size={16} /> Eintrag anlegen</button>} /><div className="admin-metrics"><AdminMetric label="Materialpositionen" value={data.materials.length} detail={`${lowStock} unter Mindestbestand`} icon={<Package size={19} />} /><AdminMetric label="Maschinen & Geräte" value={data.equipment.length} detail={`${maintenance} Wartungen in 30 Tagen`} icon={<Wrench size={19} />} /></div><div className="admin-tabs"><button className={tab === 'material' ? 'active' : ''} onClick={() => { setTab('material'); setShowForm(false); }}>Material & Lager</button><button className={tab === 'equipment' ? 'active' : ''} onClick={() => { setTab('equipment'); setShowForm(false); }}>Maschinen & Geräte</button></div>
    {showForm ? <AdminPanel title={tab === 'material' ? 'Material anlegen' : 'Gerät anlegen'}><form className="admin-form" onSubmit={submit}><div className="admin-form-grid">{tab === 'material' ? <><Field name="name" label="Bezeichnung *" required /><Field name="sku" label="Artikelnummer" /><Field name="category" label="Kategorie" /><Field name="unit" label="Einheit" defaultValue="Stück" /><Field name="stock" label="Bestand" type="number" defaultValue="0" /><Field name="minimumStock" label="Mindestbestand" type="number" defaultValue="0" /><Field name="unitCost" label="Einstandspreis netto" type="number" defaultValue="0" /><Field name="storageLocation" label="Lagerort" /></> : <><Field name="inventoryNumber" label="Inventarnummer *" required /><Field name="name" label="Bezeichnung *" required /><Field name="category" label="Kategorie" /><Field name="manufacturer" label="Hersteller" /><Field name="model" label="Modell" /><Field name="serialNumber" label="Seriennummer" /><Field name="location" label="Standort" /><Field name="nextMaintenance" label="Nächste Wartung" type="date" /></>}</div><button className="admin-button">Speichern</button></form></AdminPanel> : null}{message ? <p className="my-4 text-sm text-emerald-700">{message}</p> : null}
    <div className="mt-6"><AdminPanel title={tab === 'material' ? 'Material- und Lagerliste' : 'Maschinen- und Geräteliste'}>{loading ? <EmptyState title="Inventar wird geladen" text="Einen Moment bitte." /> : tab === 'material' ? (data.materials.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Artikel</th><th>Kategorie</th><th>Bestand</th><th>Mindestbestand</th><th>Kosten</th><th>Lagerort</th></tr></thead><tbody>{data.materials.map(item => <tr key={item.id}><td>{item.name}</td><td>{item.category || '–'}</td><td><AdminStatus tone={item.stock <= item.minimumStock ? 'danger' : 'success'}>{item.stock} {item.unit}</AdminStatus></td><td>{item.minimumStock} {item.unit}</td><td>{formatEuro(item.unitCost)}</td><td>{item.storageLocation || '–'}</td></tr>)}</tbody></table></div> : <EmptyState title="Keine Materialien" text="Pflegen Sie wiederkehrend benötigte Mittel und Verbrauchsartikel." />) : (data.equipment.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Inventarnr.</th><th>Gerät</th><th>Hersteller / Modell</th><th>Standort</th><th>Wartung</th><th>Status</th></tr></thead><tbody>{data.equipment.map(item => <tr key={item.id}><td>{item.inventoryNumber}</td><td>{item.name}</td><td>{[item.manufacturer,item.model].filter(Boolean).join(' ') || '–'}</td><td>{item.location || '–'}</td><td>{item.nextMaintenance ? new Date(item.nextMaintenance).toLocaleDateString('de-DE') : 'Nicht geplant'}</td><td><AdminStatus tone={item.status === 'einsatzbereit' ? 'success' : 'warning'}>{item.status}</AdminStatus></td></tr>)}</tbody></table></div> : <EmptyState title="Keine Geräte" text="Maschinen, Geräte und Wartungstermine werden hier verwaltet." />)}</AdminPanel></div></>;
}
function Field({ name, label, type = 'text', required, defaultValue }: { name: string; label: string; type?: string; required?: boolean; defaultValue?: string }) { return <div className="admin-field"><label>{label}</label><input name={name} type={type} required={required} defaultValue={defaultValue} step={type === 'number' ? '0.01' : undefined} /></div>; }
